### ISSUE TITLE
A notification in train.py

### ISSUE THREAD

**Issue by SHITINGCHEN** [mattroz/mobilenet_segmentation#2]
Hi, I was using your code to train my own dataset, and I found that the number of steps in a epoch is not equal to the length of generator. And this problem is caused by `steps_per_epoch` and `validation_steps` in `train.py`:
![image](https://user-images.githubusercontent.com/28386920/145315920-7e999409-becd-4463-bfb2-c6f28bde8796.png)
 Since the length of generator defined in `data_generator.py` is:
![image](https://user-images.githubusercontent.com/28386920/145315781-66e19a9c-06ab-4ee9-b708-f201c4761210.png)
SO the `steps_per_epoch` and `validation_steps` should be euqal to the LENGTH of train_generator and val_generator.

**Comment by mattroz** [comment]
Hey, @SHITINGCHEN 
You're absolutely right. Seems like I was using generator's length definition for debugging and just forgot to delete this batch size division.
Thanks for pointing this out, gonna fix it asap.

**Comment by mattroz** [comment]
#3 should fix this
